algo = input('Digite algo: ')
print(type(algo))
print('Só tem espaços? ', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É é alphanumérico?', algo.isalnum())
print('É minuscula?', algo.islower())
print('É maiúscula?', algo.isupper())
print('Está captalizada?', algo.istitle())
